<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFz4qhdy\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFz4qhdy/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFz4qhdy.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFz4qhdy\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFz4qhdy\appDevDebugProjectContainer([
    'container.build_hash' => 'Fz4qhdy',
    'container.build_id' => 'ac1554c3',
    'container.build_time' => 1566893017,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFz4qhdy');
