<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ0lphfw\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ0lphfw/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZ0lphfw.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZ0lphfw\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZ0lphfw\appProdProjectContainer([
    'container.build_hash' => 'Z0lphfw',
    'container.build_id' => '460f2981',
    'container.build_time' => 1566823230,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ0lphfw');
